package com.soundclub.models;

import java.util.HashMap;
import java.util.Map;

public class Paises {
	public static Map<String, String> lista = new HashMap<>();
	
	public static  final Map get(){
		lista.put("","");
		lista.put("AF","AfganistÃ¡n");
		lista.put("AL","Albania");
		lista.put("DE","Alemania");
		lista.put("AD","Andorra");
		lista.put("AO","Angola");
		lista.put("AI","Anguilla");
		lista.put("AQ","AntÃ¡rtida");
		lista.put("AG","Antigua y Barbuda");
		lista.put("AN","Antillas Holandesas");
		lista.put("SA","Arabia SaudÃ­");
		lista.put("DZ","Argelia");
		lista.put("AR","Argentina");
		lista.put("AM","Armenia");
		lista.put("AW","Aruba");
		lista.put("AU","Australia");
		lista.put("AT","Austria");
		lista.put("AZ","AzerbaiyÃ¡n");
		lista.put("BS","Bahamas");
		lista.put("BH","Bahrein");
		lista.put("BD","Bangladesh");
		lista.put("BB","Barbados");
		lista.put("BE","BÃ©lgica");
		lista.put("BZ","Belice");
		lista.put("BJ","Benin");
		lista.put("BM","Bermudas");
		lista.put("BY","Bielorrusia");
		lista.put("MM","Birmania");
		lista.put("BO","Bolivia");
		lista.put("BA","Bosnia y Herzegovina");
		lista.put("BW","Botswana");
		lista.put("BR","Brasil");
		lista.put("BN","Brunei");
		lista.put("BG","Bulgaria");
		lista.put("BF","Burkina Faso");
		lista.put("BI","Burundi");
		lista.put("BT","ButÃ¡n");
		lista.put("CV","Cabo Verde");
		lista.put("KH","Camboya");
		lista.put("CM","CamerÃºn");
		lista.put("CA","CanadÃ¡");
		lista.put("TD","Chad");
		lista.put("CL","Chile");
		lista.put("CN","China");
		lista.put("CY","Chipre");
		lista.put("VA","Ciudad del Vaticano (Santa Sede)");
		lista.put("CO","Colombia");
		lista.put("KM","Comores");
		lista.put("CG","Congo");
		lista.put("CD","Congo, RepÃºblica DemocrÃ¡tica del");
		lista.put("KR","Corea");
		lista.put("KP","Corea del Norte");
		lista.put("CI","Costa de MarfÃ­l");
		lista.put("CR","Costa Rica");
		lista.put("HR","Croacia (Hrvatska)");
		lista.put("CU","Cuba");
		lista.put("DK","Dinamarca");
		lista.put("DJ","Djibouti");
		lista.put("DM","Dominica");
		lista.put("EC","Ecuador");
		lista.put("EG","Egipto");
		lista.put("SV","El Salvador");
		lista.put("AE","Emiratos Ãrabes Unidos");
		lista.put("ER","Eritrea");
		lista.put("SI","Eslovenia");
		lista.put("ES","EspaÃ±a");
		lista.put("US","Estados Unidos");
		lista.put("EE","Estonia");
		lista.put("ET","EtiopÃ­a");
		lista.put("FJ","Fiji");
		lista.put("PH","Filipinas");
		lista.put("FI","Finlandia");
		lista.put("FR","Francia");
		lista.put("GA","GabÃ³n");
		lista.put("GM","Gambia");
		lista.put("GE","Georgia");
		lista.put("GH","Ghana");
		lista.put("GI","Gibraltar");
		lista.put("GD","Granada");
		lista.put("GR","Grecia");
		lista.put("GL","Groenlandia");
		lista.put("GP","Guadalupe");
		lista.put("GU","Guam");
		lista.put("GT","Guatemala");
		lista.put("GY","Guayana");
		lista.put("GF","Guayana Francesa");
		lista.put("GN","Guinea");
		lista.put("GQ","Guinea Ecuatorial");
		lista.put("GW","Guinea-Bissau");
		lista.put("HT","HaitÃ­");
		lista.put("HN","Honduras");
		lista.put("HU","HungrÃ­a");
		lista.put("IN","India");
		lista.put("ID","Indonesia");
		lista.put("IQ","Irak");
		lista.put("IR","IrÃ¡n");
		lista.put("IE","Irlanda");
		lista.put("BV","Isla Bouvet");
		lista.put("CX","Isla de Christmas");
		lista.put("IS","Islandia");
		lista.put("KY","Islas CaimÃ¡n");
		lista.put("CK","Islas Cook");
		lista.put("CC","Islas de Cocos o Keeling");
		lista.put("FO","Islas Faroe");
		lista.put("HM","Islas Heard y McDonald");
		lista.put("FK","Islas Malvinas");
		lista.put("MP","Islas Marianas del Norte");
		lista.put("MH","Islas Marshall");
		lista.put("UM","Islas menores de Estados Unidos");
		lista.put("PW","Islas Palau");
		lista.put("SB","Islas SalomÃ³n");
		lista.put("SJ","Islas Svalbard y Jan Mayen");
		lista.put("TK","Islas Tokelau");
		lista.put("TC","Islas Turks y Caicos");
		lista.put("VI","Islas VÃ­rgenes (EEUU)");
		lista.put("VG","Islas VÃ­rgenes (Reino Unido)");
		lista.put("WF","Islas Wallis y Futuna");
		lista.put("IL","Israel");
		lista.put("IT","Italia");
		lista.put("JM","Jamaica");
		lista.put("JP","JapÃ³n");
		lista.put("JO","Jordania");
		lista.put("KZ","KazajistÃ¡n");
		lista.put("KE","Kenia");
		lista.put("KG","KirguizistÃ¡n");
		lista.put("KI","Kiribati");
		lista.put("KW","Kuwait");
		lista.put("LA","Laos");
		lista.put("LS","Lesotho");
		lista.put("LV","Letonia");
		lista.put("LB","LÃ­bano");
		lista.put("LR","Liberia");
		lista.put("LY","Libia");
		lista.put("LI","Liechtenstein");
		lista.put("LT","Lituania");
		lista.put("LU","Luxemburgo");
		lista.put("MK","Macedonia, Ex-RepÃºblica Yugoslava de");
		lista.put("MG","Madagascar");
		lista.put("MY","Malasia");
		lista.put("MW","Malawi");
		lista.put("MV","Maldivas");
		lista.put("ML","MalÃ­");
		lista.put("MT","Malta");
		lista.put("MA","Marruecos");
		lista.put("MQ","Martinica");
		lista.put("MU","Mauricio");
		lista.put("MR","Mauritania");
		lista.put("YT","Mayotte");
		lista.put("MX","MÃ©xico");
		lista.put("FM","Micronesia");
		lista.put("MD","Moldavia");
		lista.put("MC","MÃ³naco");
		lista.put("MN","Mongolia");
		lista.put("MS","Montserrat");
		lista.put("MZ","Mozambique");
		lista.put("NA","Namibia");
		lista.put("NR","Nauru");
		lista.put("NP","Nepal");
		lista.put("NI","Nicaragua");
		lista.put("NE","NÃ­ger");
		lista.put("NG","Nigeria");
		lista.put("NU","Niue");
		lista.put("NF","Norfolk");
		lista.put("NO","Noruega");
		lista.put("NC","Nueva Caledonia");
		lista.put("NZ","Nueva Zelanda");
		lista.put("OM","OmÃ¡n");
		lista.put("NL","PaÃ­ses Bajos");
		lista.put("PA","PanamÃ¡");
		lista.put("PG","PapÃºa Nueva Guinea");
		lista.put("PK","PaquistÃ¡n");
		lista.put("PY","Paraguay");
		lista.put("PE","PerÃº");
		lista.put("PN","Pitcairn");
		lista.put("PF","Polinesia Francesa");
		lista.put("PL","Polonia");
		lista.put("PT","Portugal");
		lista.put("PR","Puerto Rico");
		lista.put("QA","Qatar");
		lista.put("UK","Reino Unido");
		lista.put("CF","RepÃºblica Centroafricana");
		lista.put("CZ","RepÃºblica Checa");
		lista.put("ZA","RepÃºblica de SudÃ¡frica");
		lista.put("DO","RepÃºblica Dominicana");
		lista.put("SK","RepÃºblica Eslovaca");
		lista.put("RE","ReuniÃ³n");
		lista.put("RW","Ruanda");
		lista.put("RO","Rumania");
		lista.put("RU","Rusia");
		lista.put("EH","Sahara Occidental");
		lista.put("KN","Saint Kitts y Nevis");
		lista.put("WS","Samoa");
		lista.put("AS","Samoa Americana");
		lista.put("SM","San Marino");
		lista.put("VC","San Vicente y Granadinas");
		lista.put("SH","Santa Helena");
		lista.put("LC","Santa LucÃ­a");
		lista.put("ST","Santo TomÃ© y PrÃ­ncipe");
		lista.put("SN","Senegal");
		lista.put("SC","Seychelles");
		lista.put("SL","Sierra Leona");
		lista.put("SG","Singapur");
		lista.put("SY","Siria");
		lista.put("SO","Somalia");
		lista.put("LK","Sri Lanka");
		lista.put("PM","St Pierre y Miquelon");
		lista.put("SZ","Suazilandia");
		lista.put("SD","SudÃ¡n");
		lista.put("SE","Suecia");
		lista.put("CH","Suiza");
		lista.put("SR","Surinam");
		lista.put("TH","Tailandia");
		lista.put("TW","TaiwÃ¡n");
		lista.put("TZ","Tanzania");
		lista.put("TJ","TayikistÃ¡n");
		lista.put("TF","Territorios franceses del Sur");
		lista.put("TP","Timor Oriental");
		lista.put("TG","Togo");
		lista.put("TO","Tonga");
		lista.put("TT","Trinidad y Tobago");
		lista.put("TN","TÃºnez");
		lista.put("TM","TurkmenistÃ¡n");
		lista.put("TR","TurquÃ­a");
		lista.put("TV","Tuvalu");
		lista.put("UA","Ucrania");
		lista.put("UG","Uganda");
		lista.put("UY","Uruguay");
		lista.put("UZ","UzbekistÃ¡n");
		lista.put("VU","Vanuatu");
		lista.put("VE","Venezuela");
		lista.put("VN","Vietnam");
		lista.put("YE","Yemen");
		lista.put("YU","Yugoslavia");
		lista.put("ZM","Zambia");
		lista.put("ZW","Zimbabue");
		
		return lista;
	}
}
